<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
     foreach ($peliculas as $pelicula) {
                $titulo = ($pelicula->getTitulo()); // escapar espacios
                echo "<li><a href='index.php?titulo={$titulo}'>{$pelicula->getTitulo()}</a></li>";}
    ?>
</body>
</html>