<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="styles/styles.css">
</head>
<body>
    <h1>VIDEO CLUB</h1>
    <ul>
    <?php

    if($_SESSION['user']){
        echo "<h3>Usuario: {$_SESSION['user']->getUsername()}</h3>";
        foreach ($peliculas as $pelicula) {
                $id = ($pelicula->getId());// escapar espacios
                echo "<li><a href='index.php?id={$id}'>{$pelicula->getTitle()}</a></li>";}
        echo "<br><a href='index.php?c=movie&action=addMovie'>Agregar película</a>";
        echo "<br><a href='index.php?c=login&logout=1'>Cerrar sesión</a>";
    }
    ?>
    </ul>
</body>
</html>