<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>VIDEO CLUB</h1>
    <ul>
    <?php
     foreach ($peliculas as $pelicula) {
                $id = ($pelicula->getId());// escapar espacios
                echo "<li><a href='index.php?id={$id}'>{$pelicula->getTitle()}</a></li>";}
    ?>
    </ul>
</body>
</html>