<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>REGISTRATE</h1>
    <form action="index.php" method="post">
        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username">
        <br>
        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password">
        <br>
        <label for="password">Confirmar Contraseña:</label>
        <input type="password" id="password" name="password">
        <br>
        <input type="submit" value="Registrarse" name="Registrar">
        </form>


</body>
</html>