<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
    if(!$error){
        echo "<h2>Título: {$pelicula->getTitle()}</h2>";
        echo "<p>Director: {$pelicula->getDirector()}</p>";
        echo "<p>Año: {$pelicula->getYear()}</p>";
        echo "<img src='public/img/{$pelicula->getTitle()}.webp'/>";
        echo "<br><a href='index.php'>Volver</a>";
    }else{
        echo '<script>alert("'.$error.'")</script>';
    }
    ?>
</body>
</html>