<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
    foreach ($peliculas as $pelicula) {
                    if ($pelicula->getTitulo() == $_GET["titulo"]) {
                        echo "<h2>Título: {$pelicula->getTitulo()}</h2>";
                        echo "<p>Director: {$pelicula->getDirector()}</p>";
                        echo "<p>Año: {$pelicula->getAnio()}</p>";
                        echo "<img src='public/img/{$pelicula->getTitulo()}.webp'/>";
                        echo "<br><a href='index.php'>Volver</a>";
                        break;
                    }
            }
        ?>
</body>
</html>